import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Provider } from 'jotai'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "AI Messenger",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en">
        <body className={inter.className}>
          <div id="root">
            {children}
          </div>
        </body>
      </html>
    </Provider>
  )
}
